### ISSUE TITLE
Document keyboard connector/receptical type and manufacturer

### ISSUE THREAD

**Issue by sladen** [rampadc/arduino-thinkpadkb-usb#2]
The physical interface is a 40-pin board-to-board connector. Ideally the type and source of this connector would be documented in the source code and documentation.

The page at:

* https://hackaday.com/2014/04/30/using-a-thinkpad-keyboard-over-usb/

states:

> "The connector is an extremely odd proprietary deal, that can be found through the usual channels for about $5 in quantity 100."

Another source suggestions that the connector is not proprietary, but just out of production was only generally produced in large batches for IBM/Lenovo.

**Comment by sladen** [comment]
According to:

* http://www.instructables.com/id/Make-a-ThinkPad-keyboard-USB-adapter-with-Arduino/

it is a:

> JAE AA01B-S040VA1-R3000

Further discussion in the page at:

* https://electronics.stackexchange.com/questions/64112/how-to-find-socket-for-keyboard-connector

suggests that a compatible alternative is:

> Molex SlimStack 54363-0478

The current Molex 54363 revision appears to be:

* https://www.molex.com/molex/products/datasheet.jsp?part=active/0543630489_PCB_RECEPTACLES.xml

**Comment by sladen** [comment]
According to:

* http://www.instructables.com/id/Make-a-ThinkPad-keyboard-USB-adapter-with-Arduino/

it is a:

> JAE AA01B-S040VA1-R3000

Further discussion in the page at:

* https://electronics.stackexchange.com/questions/64112/how-to-find-socket-for-keyboard-connector

suggests that a compatible alternative is:

> Molex SlimStack 54363-0478

The current Molex 54363 revision appears to be:

* https://www.molex.com/molex/products/datasheet.jsp?part=active/0543630489_PCB_RECEPTACLES.xml

However, somebody who tried to get the Molex to work notes whilst the the pitch and depth work, there are mating complications with the plastic walling around the top and bottom edges of the connector.

**Comment by sladen** [comment]
In the following webpage @mtfurlan documents their own exploration, and suggests that a:

> WM6787CT-ND

can be used as a substitute.

**Comment by sladen** [comment]
In the following webpage on which @mtfurlan documents their own exploration:

* https://www.tomesoftware.com/usb-thinkpad-laptop-keyboard/

and suggests that a:

> WM6787CT-ND

can be used as a substitute.

**Comment by rampadc** [comment]
This is not a software issue. ThinkPad T60 uses JAE AA01B-S040VA1 receptacles and is stated so in IBM ThinkPad T60 schematics.

**Comment by sladen** [comment]
@rampadc, thanks for the confirmation, now that this is confirmed, it probably makes sense to add this to the section "Parts List" in `README.md`.  Currently this lists the other components, but just not the most critical/important one (the JAE AA01B-S040VA1 receptacle itself).
