### ISSUE TITLE
JAE AA01B-S040VA1 EAGLE library

### ISSUE THREAD

**Issue by martonmiklos** [rampadc/arduino-thinkpadkb-usb#3]
Hi @rampadc ,

First of all I appologize for opening this here, (since it is not related to the SW).

Could you please share with me the Lenovo connector EAGLE library? 
If you can share any of the PCBs that would be fine as well.

Thanks in advance!

**Comment by rampadc** [comment]
Never used Eagle, never will.

**Comment by martonmiklos** [comment]
Is not this project made by you?
https://www.instructables.com/id/Make-a-ThinkPad-keyboard-USB-adapter-with-Arduino

It looks like EAGLE, but I might mistaken. 
If you can share the footprint in any format that would be great I might be able to import it.

**Comment by rampadc** [comment]
Haha good catch. It's been so long I forgot I used Eagle once upon a time. The only remaining project files I could dig up are placed here: [https://archiveworthy.wordpress.com/2015/02/28/thinkclamp-bluetooth-project-ceased/](https://archiveworthy.wordpress.com/2015/02/28/thinkclamp-bluetooth-project-ceased/)

**Comment by martonmiklos** [comment]
Aha, you have used Altium for the BT one. So do I understand correctly that the PDF schematics is the only thing what you have from that project.

**Comment by rampadc** [comment]
Yes
